FROM prom/prometheus:latest

# Install envsubst utility
USER root
RUN apk add --no-cache gettext

# Copy Prometheus config
COPY prometheus.yml /etc/prometheus/prometheus.yml

# Use envsubst to replace variables before starting Prometheus
CMD /bin/sh -c "envsubst < /etc/prometheus/prometheus.yaml > /tmp/prometheus.yaml && exec prometheus --config.file=/tmp/prometheus.yaml --web.enable-lifecycle --storage.tsdb.path=/prometheus"
